# Reference: https://docs.gradle.org/current/userguide/platforms.html

[versions]

[plugins]

[libraries]

aws-sdk-kotlin-v1-bom = { module = "aws.sdk.kotlin:bom", version = "1.0.48" }
aws-sdk-kotlin-v1-codeartifact = { module = "aws.sdk.kotlin:codeartifact" }

google-tink = { module = "com.google.crypto.tink:tink", version = "1.12.0" }

jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version = "2.16.1" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-datatype-jsr310 = { module="com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

pearx-kasechange = { module = "net.pearx.kasechange:kasechange", version = "1.4.1" }

